### ISSUE TITLE
Adding asdf for version management

### ISSUE THREAD

**Issue by octosteve** [github/homebrew-bootstrap#100]
[asdf](https://github.com/asdf-vm/asdf) offers a way of managing version managers.

Are we open to supporting its installation for setup scripts? It has a [brew formula](https://formulae.brew.sh/formula/asdf).

**Comment by MikeMcQuaid** [comment]
@octosteve Can you explain more specifically what you'd like to see/do? Thanks!

**Comment by octosteve** [comment]
Thanks for responding. I think something around supporting `asdf` as an option for setting up dependencies. That said, I think it'd be a pretty big lift to support another package manager in _all_ of our scripts, but it would be nice!

**Comment by MikeMcQuaid** [comment]
> That said, I think it'd be a pretty big lift to support another package manager in _all_ of our scripts

Agreed, passing on this for now given that. Note that e.g. `rbenv` doesn't need to be used as your version manager; if `asdf` makes `which ruby` return the correct one then you can use it. `rbenv` will still need to be installed (but not its shims) just in order to detect the correct Ruby and install it if necessary.
