### ISSUE TITLE
brew-upgrade-mysql check failing due to "newer" brew version

### ISSUE THREAD

**Issue by tomkrouper** [github/homebrew-bootstrap#81]
MySQL is attempting to upgrade every time this runs due to a [change](https://github.com/Homebrew/homebrew-core/commit/b70ab71790bc42e8ad115bcd87b2a88e8d25cd88) in homebrew-core which created a revision "1" which causes the issue below.

```
[:~/github/homebrew-bootstrap] master ± brew info mysql@5.7 --json=v1 | jq -r ".[] | .installed[-1].version"
5.7.27_1
[:~/github/homebrew-bootstrap] master ± brew info mysql@5.7 --json=v1 | jq -r ".[] | .versions.stable"
5.7.27
```
Affected code: 
https://github.com/github/homebrew-bootstrap/blob/791a4078dda719fe9f333b9664c3d4417bf920e8/cmd/brew-upgrade-mysql#L30-L32

I'm not sure if this is a homebrew error with `.versions.stable` not matching the `.installed[-1].version`, or if this is something we'd need to account for.

@MikeMcQuaid, sorry to single you out, is this a homebrew or "us" issue?

**Comment by MikeMcQuaid** [comment]
> I'm not sure if this is a homebrew error with `.versions.stable` not matching the `.installed[-1].version`

This is intentional (although somewhat non-ideal): for this comparison you need to compare `.versions.stable` with `_` and `.revision` appended to `brew info mysql@5.7 --json=v1 | jq -r ".[] | .installed[-1].version"`.

I'd suggest instead relying the exit code of `brew outdated mysql` instead, though. That will get you what you're trying to achieve without having to parse JSON. Additionally, `brew upgrade mysql@${mysql_version} || true` seems like a bad idea as you're going to silently continue even if the upgrade fails?

Hope that's useful!

**Comment by tomkrouper** [comment]
> I'd suggest instead relying the exit code of `brew outdated mysql` instead

That makes a lot of sense.

> Additionally, `brew upgrade mysql@${mysql_version} || true` seems like a bad idea as you're going to silently continue even if the upgrade fails?

It has saved folks from being stuck until a fix came along for this issue. Right now, it is just ugly output during bootstrapping. However, I agree it is bad. I'll make a change to it.
